-- Maak de voorraad tabel aan
create table Voorraad (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    categorie text,
    naam_kort text,
    omschrijving text,
    hoeveelheid numeric,
    eenheid text,
    kcal_per_eenheid numeric,
    eiwit_per_eenheid numeric,
    tht date,
    datum_laatste_wijziging timestamp with time zone default now(),
    opmerkingen text
);
